

INSERT ALL
into HOSPITACJA (IDHOSPITACJI,TERMIN,KTONADZOROWANY) values ('1',to_date('19/07/24','RR/MM/DD'),null)
into HOSPITACJA (IDHOSPITACJI,TERMIN,KTONADZOROWANY) values ('2',to_date('19/11/24','RR/MM/DD'),null)
SELECT * FROM dual;


INSERT ALL
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('1','1','1','Ala','Bednar','magister','3543,122')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('2','2','2','Weronika','Warsiewicz','licencjatka','1452')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('3','1','1','Anna','Sroka','nieznane','1300')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('4','2','1','Robert','Makłowicz','szkoła zawodowa','6000,12')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('5','2','1','Joanna','Wiśnia','Kwalifikacje uznane za wystarczajace do pelnienia danej funkcji obozowej','123')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('6','2','1','Roksana','Rolnikow','szkoła wyższa','3000')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('7','2','1','Mirosław','Pumpernikiel','brak','20')
	 into PRZEDSZKOLANKA (IDPRAC,NAZWAGRUPY,HOS_IDHOS,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('8','2','1','Zdzisława','Potylica','kurs pedagogiczny','2500')
SELECT * FROM dual;

Insert ALL 
 into SEKRETARKA (IDPRAC,GODZROZPOCZECIAPRACY,GODZZAKONCZENIAPRACY,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('1',null,null,'Anna','Kozłowska','magister','1500')
 into SEKRETARKA (IDPRAC,GODZROZPOCZECIAPRACY,GODZZAKONCZENIAPRACY,IMIE,NAZWISKO,KWALIFIKACJE,PLACA) values ('2',to_date('70/01/01','RR/MM/DD'),to_date('70/01/01','RR/MM/DD'),'Franciszek','Apollo','naukowiec NASA','399,99')
SELECT * FROM dual;
 
INSERT ALL
	into GRUPAPRZEDSZKOLNA (IDGRUPY,SALA,NAZWA,WIEKDZIECI,IDPRAC) values ('1','3','muchomorki',null,'1')
	into GRUPAPRZEDSZKOLNA (IDGRUPY,SALA,NAZWA,WIEKDZIECI,IDPRAC) values ('2','5','krasnoludki','5','3') 
	into GRUPAPRZEDSZKOLNA (IDGRUPY,SALA,NAZWA,WIEKDZIECI,IDPRAC) values ('3','8','elfy','6','3')
	into GRUPAPRZEDSZKOLNA (IDGRUPY,SALA,NAZWA,WIEKDZIECI,IDPRAC) values ('4','12','smerfy','4','3') 
SELECT * FROM dual;
 
 
Insert ALL
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('1','sniadanie',null,null)
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('2','obiad',null,null)
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('3','obiad',null,'wegetariańska')
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('4','kolacja',null,null)
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('5','podwieczorek',null,'jarska')
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('6','kolacja',null,'wegańska')
 into POSILEK (IDPOSILKU,NAZWA,GODZROZWOZENIA,DIETA) values ('7','śniadanie',null,'brak')
select * from dual;

 
 INSERT ALL
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('1','Ala','Bednarczyk',to_date('15/11/01','RR/MM/DD'),'4','1')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('2','Marek','Kukla',to_date('14/01/15','RR/MM/DD'),'2','2')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('3','Karol','Kaminski',to_date('15/06/22','RR/MM/DD'),'4','3')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('4','Adam','Kukcinski',to_date('13/03/15','RR/MM/DD'),'3','4')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('5','Bartosz','Bułka',to_date('13/01/01','RR/MM/DD'),'3','5')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('6','Witold','Motyl',to_date('14/01/01','RR/MM/DD'),'2','6')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('7','Maja','Kajko',to_date('15/01/01','RR/MM/DD'),'4','7')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('8','Paskal','Wyż',to_date('15/01/01','RR/MM/DD'),'4','3')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('9','Adam','Kapusta',to_date('13/01/01','RR/MM/DD'),'3','4')
	 into DZIECKO (IDDZIECKA,IMIE,NAZWISKO,DATAURODZENIA,GRUPAPRZEDSZKOLNA_IDGRUPY,POSILEK_IDPOSILKU) values ('10','Piotr','Golonka',to_date('14/01/01','RR/MM/DD'),'2','6')
SELECT * FROM dual;



INSERT ALL
into FESTYN (IDFESTYNU,GRUPAWYSTEPUJACA,OSOBAODPOWIEDZIALNA,TERMINWYDARZENA,HASLO) values ('1','2','1',to_date('20/01/12','RR/MM/DD'),'Witaj świecie!')
into FESTYN (IDFESTYNU,GRUPAWYSTEPUJACA,OSOBAODPOWIEDZIALNA,TERMINWYDARZENA,HASLO) values ('2','3','2',to_date('19/07/21','RR/MM/DD'),'Wakacje')
SELECT * FROM dual;


INSERT ALL
 into ZAJECIADODATKOWE (IDZAJECIA,RODZAJ,DATAPROWADZENIA,OPLATY,CZASTYGODNIOWO,DLAKOGO) values ('1','muzyka',null,null,'45',null)
 into ZAJECIADODATKOWE (IDZAJECIA,RODZAJ,DATAPROWADZENIA,OPLATY,CZASTYGODNIOWO,DLAKOGO) values ('2','plastyka',to_date('70/01/01','RR/MM/DD'),'1','2','2')
SELECT * FROM dual;

INSERT ALL
 into OPLATA (IDOPLATY,WIELKOSC,PRZEDMIOTOPLATY,CZESTOSC,ZAJECIADODATKOWE_IDZAJECIA,POMOCDYDAKTYCZNA_IDPOMOCY,POMOCDYDAKTYCZNA_IDPRAC,POMOCDYDAKTYCZNA_IDGRUPY) values ('1','10','zaj dod',         '4','1',null,'5','1')
 into OPLATA (IDOPLATY,WIELKOSC,PRZEDMIOTOPLATY,CZESTOSC,ZAJECIADODATKOWE_IDZAJECIA,POMOCDYDAKTYCZNA_IDPOMOCY,POMOCDYDAKTYCZNA_IDPRAC,POMOCDYDAKTYCZNA_IDGRUPY) values ('2','200','naprawa kranu', '1', '2',null,null,null)
SELECT * FROM dual;


INSERT ALL
into POMOCDYDAKTYCZNA (IDPOMOCY,RODZAJ,DODATKOWEOPLATY,GRUPADOCELOWA,OSOBAODPOWIEDZIALNA,OPLATA_IDOPLATY,PRZEDSZKOLANKA_IDPRAC,GRUPAPRZEDSZKOLNA_IDGRUPY) values ('1','ksiazki','20',null,null,null,'1','1')
into POMOCDYDAKTYCZNA (IDPOMOCY,RODZAJ,DODATKOWEOPLATY,GRUPADOCELOWA,OSOBAODPOWIEDZIALNA,OPLATA_IDOPLATY,PRZEDSZKOLANKA_IDPRAC,GRUPAPRZEDSZKOLNA_IDGRUPY) values ('2','przybory geometryczne',null,'2',null,null,'2','3')
SELECT * FROM dual;



INSERT ALL
 into ZEBRANIEZRODZICAMI (IDZEBRANIA,DATA,GRUPA,MIEJSCA,PROWADZACYZEBRANIE,CZYOBOWIAZKOWE,PRZEDSZKOLANKA_IDHOSPITACJI) values ('1',to_date('21/01/12','RR/MM/DD'),'1','3','1','1','1')
 into ZEBRANIEZRODZICAMI (IDZEBRANIA,DATA,GRUPA,MIEJSCA,PROWADZACYZEBRANIE,CZYOBOWIAZKOWE,PRZEDSZKOLANKA_IDHOSPITACJI) values ('2',to_date('70/01/01','RR/MM/DD'),'2','5','2','true','1')
 into ZEBRANIEZRODZICAMI (IDZEBRANIA,DATA,GRUPA,MIEJSCA,PROWADZACYZEBRANIE,CZYOBOWIAZKOWE,PRZEDSZKOLANKA_IDHOSPITACJI) values ('3',null,null,null,null,null,'1')
SELECT * FROM dual;